# Stage 1: Build the app
ARG NODE_VERSION=23
FROM node:${NODE_VERSION} AS build

WORKDIR /usr/src/app
ARG BACKEND_URL
ENV BACKEND_URL ${BACKEND_URL}
COPY .yarnrc.yml ./
COPY .yarn ./.yarn
COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN echo "export const environment = { production: true, BACKEND_URL: '$BACKEND_URL' };" >> /usr/src/app/apps/web/src/environments/environment.prod.ts

RUN npx nx run web:build:production

FROM node:${NODE_VERSION}-alpine

COPY --from=build /usr/src/app/dist/apps/web /usr/src/app

EXPOSE 4200

CMD ["node", "/usr/src/app/server/server.mjs"]
