services:
  postgres:
    restart: unless-stopped
    image: postgres:17-alpine
    container_name: Astolfo-postgres-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    
volumes:
  postgres-dev-data: