x-logging: &default-logging
  driver: 'json-file'
  options:
    max-file: '5'
    max-size: '10m'

services:
  postgres:
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    restart: unless-stopped
    image: postgres:17-alpine
    container_name: Astolfo-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - astolfo-network

  astolfo:
    logging: *default-logging
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile.bot
      args:
        - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    container_name: Astolfo-bot
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - OWNER=${OWNER}
      - DEFAULT_PREFIX=${DEFAULT_PREFIX}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - PORT=${PORT}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - CLIENT_URL=${CLIENT_URL}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3003:3000'
    networks:
      - astolfo-network
    volumes:
      - ./libs/models/prisma:/app/libs/models/prisma

  prometheus:
    image: prom/prometheus:latest
    container_name: Astolfo-prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - astolfo-network

  grafana:
    image: grafana/grafana:latest
    container_name: Astolfo-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - '3030:3000'
    depends_on:
      - prometheus
    networks:
      - astolfo-network

networks:
  astolfo-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
  postgres-data:
