version: '3.8'
services:
  astolfo:
    build: .
    container_name: Astolfo-bot
    restart: always
    environment:
      - DATABASE_URL
      - DISCORD_CLIENT_ID
      - DISCORD_BOT_TOKEN
      - DISCORD_PUBLIC_KEY
      - DISCORD_CLIENT_SECRET
      - OWNER
    ports:
      - "3003:3000"