version: '3.8'
services:
  mongodb:
    image: mongo:4.4.15
    volumes:
      - ts-profile-gen-server:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
volumes:
  ts-profile-gen-server:
    external: true
