# This is a basic workflow to help you get started with Actions

name: Selfhosted discordBot build

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  express:
    runs-on: self-hosted
    environment: .env    

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: stop old express container
        run: docker stop astolfo-bot || true

      - name: Remove old express container
        run: docker rm -f astolfo-bot


      - name: Remove old docker image
        run: docker rmi -f astolfo-bot

      - name: Build docker image
        run: docker build -t astolfo-bot .

      - name: Run docker image
        run: docker run -d --restart unless-stopped --name astolfo-bot astolfo-bot

      - name: Cleanup old docker images
        run: docker image prune -af
