# This is a basic workflow to help you get started with Actions

name: run docker build

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: .env    

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Build
        run: docker build -t astolfo-bot .

      - name: goto directory
        run: cd ${{ secrets.workspace }}
        working-directory: ${{ secrets.workspace }}

      - name: docker-compose pull
        run: docker-compose pull

      - name: up docker-compose
        run: docker-compose up -d
