# This is a basic workflow to help you get started with Actions

name: run docker build

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: .env    

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t astolfo-bot .

      - name: pull docker-compose
        run: docker-compose pull

      - name: up docker-compose
        run: docker-compose up -d
