# This is a basic workflow to help you get started with Actions

name: run docker build

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" >> .env
          echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" >> .env
          echo "DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }}" >> .env
          echo "DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }}" >> .env
          echo "OWNER=${{ secrets.OWNER }}" >> .env

      - name: check location
        run: pwd

      - name: docker-compose build
        run: docker-compose build

      - name: up docker-compose
        run: docker-compose up -d

      - name: clean up docker images
        run: docker image prune -f
