# This is a basic workflow to help you get started with Actions

name: run docker build

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: .env
    permissions:
      contents: read
      packages: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run astolfo-bot
        run: docker compose up -d --build
        env:
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          OWNER: ${{ secrets.OWNER }}
          DEFAULT_PREFIX: ${{ secrets.DEFAULT_PREFIX }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: ${{ secrets.PORT }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          PORT_WEB: ${{ secrets.PORT_WEB }}
      - name: clean up docker images
        run: docker image prune -f
